Add component CommentsList
wolox-training/afz-react-native pull request #6
Opened 2020-12-30 20:46 UTC by andreszuluaga-wolox

## Summary

Add component CommentsList.

## Screenshots

### Android

#### Galaxy S (or similar)
![WhatsApp Image 2020-12-30 at 3 45 11 PM](https://user-images.githubusercontent.com/75996952/103380224-3a723a80-4ab6-11eb-99fd-7023d51fa510.jpeg)

#### Pixel 2/3 (or similar)
![Screenshot_1609360736](https://user-images.githubusercontent.com/75996952/103379880-2974f980-4ab5-11eb-8397-5c546d9e7360.png)

#### Pixel 3XL (or similar)
![Screenshot_1609360842](https://user-images.githubusercontent.com/75996952/103379945-6214d300-4ab5-11eb-9658-1417de769897.png)

### iOS

#### iPhone SE (or similar)
![simulator_screenshot_0FA1C43D-0B79-4C91-9899-D82DF93CA283](https://user-images.githubusercontent.com/75996952/103379852-119d7580-4ab5-11eb-9263-12613d18b5e4.png)

#### iPhone 8 (or similar)
![simulator_screenshot_D342D054-71F9-4909-9D90-9B81BA0A4BB7](https://user-images.githubusercontent.com/75996952/103379927-50333000-4ab5-11eb-8a8b-aa959c940973.png)

#### iPhone 11 (or similar)
![simulator_screenshot_FB1485F8-8DC2-41C0-9BB5-6653D492ACEF](https://user-images.githubusercontent.com/75996952/103379738-a3f14980-4ab4-11eb-85fc-0eca312a5afc.png)

## Trello Card

https://trello.com/c/rhZtfF80/16-n-73-tabla-de-comentarios

2021-01-01 16:28 UTC, guidoprinc requested changes
I think that the comments list should be below the detail of the book, not in another screen. Check that

2021-01-01 16:28 UTC, guidoprinc commented on wbooks/src/app/components/CommentsList/index.tsx
> +    setLimit(5);
this should show all (the maximum amount), not just 5

2021-01-01 16:28 UTC, guidoprinc commented on wbooks/src/app/components/CommentsBook/index.tsx
> +          <Text style={styles.author}>{text}</Text>
use appropriate names for this styles

2021-01-01 16:28 UTC, guidoprinc commented on wbooks/src/app/components/CommentsBook/index.tsx
> +          <Text style={styles.author}>{text}</Text>
check the image, they are not the same as the BookItem

2021-01-01 16:28 UTC, guidoprinc commented on wbooks/src/app/components/CommentsBook/styles.ts
> +    height: 50,
extract this common constant inside this file

2021-01-01 16:28 UTC, guidoprinc commented on wbooks/src/app/components/CommentsBook/styles.ts
> +    height: 50,
use it for `borderRadius` too

2021-01-04 11:52 UTC, andreszuluaga-wolox commented on wbooks/src/app/components/CommentsList/index.tsx
> +    setLimit(5);
Ok. The card say, last 5. But not import, I fix it

2021-01-04 13:57 UTC, guidoprinc requested changes

2021-01-04 13:57 UTC, guidoprinc commented on wbooks/src/app/index.tsx
> +        <Stack.Screen name="CommentsList" component={CommentsList} />
this should be a component inside bookdetail

2021-01-04 17:26 UTC, guidoprinc requested changes

2021-01-04 17:26 UTC, guidoprinc commented on wbooks/src/app/index.tsx
> +        <Stack.Screen name="CommentsList" component={CommentsList} />
remove this line

2021-01-04 20:17 UTC, guidoprinc approved these changes

2021-01-04 20:30 UTC, merged